export interface Currency {
    key: string
    value: string,
    flag?: string,
    icon?: string
    text: string,
    img: string,
    alias: string,
    isCrypto: boolean,
    symbol: string,
    priority: number,
    decimals: number,
    isActive: boolean,
    protocols?: string[]
}

interface Currencies {
    [key: string]: Currency;
}

export const currencies: Currencies = {
    BRL: {
        key: 'br',
        value: 'BRL',
        flag: 'br',
        text: 'Real Brasileño',
        img: 'brazil',
        alias: 'BRL',
        isCrypto: false,
        symbol: 'R$',
        priority: 10,
        decimals: 2,
        isActive: false,
    },
    CLP: {
        key: 'cl',
        value: 'CLP',
        flag: 'cl',
        text: 'Peso Chileno',
        img: 'chile',
        alias: 'CLP',
        isCrypto: false,
        symbol: 'CL$',
        priority: 6,
        decimals: 2,
        isActive: true,
    },
    COP: {
        key: 'co',
        value: 'COP',
        flag: 'co',
        text: 'Peso Colombiano',
        img: 'colombia',
        alias: 'COP',
        isCrypto: false,
        symbol: 'COL$',
        priority: 5,
        decimals: 2,
        isActive: true,
    },
    EUR: {
        key: 'es',
        value: 'EUR',
        flag: 'es',
        text: 'Euro',
        img: 'europa',
        alias: 'EUR',
        isCrypto: false,
        symbol: '€',
        priority: 7,
        decimals: 2,
        isActive: true,
    },
    DOD: {
        key: 'do',
        value: 'DOD',
        flag: 'do',
        text: 'Dolar Dominicano',
        img: 'dominicana',
        alias: 'DOD',
        isCrypto: false,
        symbol: 'RD$',
        priority: 9,
        decimals: 2,
        isActive: false,
    },
    DOP: {
        key: 'dop',
        value: 'DOP',
        flag: 'do',
        text: 'Peso Dominicano',
        img: 'dominicana',
        alias: 'DOP',
        isCrypto: false,
        symbol: 'RD$',
        priority: 9,
        decimals: 2,
        isActive: true,
    },
    PEN: {
        key: 'pe',
        value: 'PEN',
        flag: 'pe',
        text: 'Sol Peruano',
        img: 'peru',
        alias: 'PEN',
        isCrypto: false,
        symbol: 'S/',
        priority: 8,
        decimals: 2,
        isActive: true,
    },
    PE_USD: {
        key: 'pe_usd',
        value: 'PE_USD',
        flag: 'pe_usd',
        text: 'Dolar Peruano',
        img: 'peru',
        alias: 'PE_USD',
        isCrypto: false,
        symbol: '$',
        priority: 8,
        decimals: 2,
        isActive: false,
    },
    PE_EUR: {
        key: 'pe_eur',
        value: 'PE_EUR',
        flag: 'pe_eur',
        text: 'Euro Peruano',
        img: 'peru',
        alias: 'PE_EUR',
        isCrypto: false,
        symbol: '€',
        priority: 8,
        decimals: 2,
        isActive: false,
    },
    USD: {
        key: 'us',
        value: 'USD',
        flag: 'us',
        text: 'US Dollar',
        img: 'usa',
        alias: 'USD',
        isCrypto: false,
        symbol: '$',
        priority: 1,
        decimals: 2,
        isActive: true,
    },
    VES: {
        key: 've',
        value: 'VES',
        flag: 've',
        text: 'Bolívar Venezolano',
        img: 'venezuela',
        alias: 'VES',
        isCrypto: false,
        symbol: 'Bs.',
        priority: 2,
        decimals: 2,
        isActive: true,
    },
    ARS: {
        key: 'ar',
        value: 'ARS',
        flag: 'ar',
        text: 'Peso Argentino',
        img: 'argentina',
        alias: 'ARS',
        isCrypto: false,
        symbol: 'Ar$',
        priority: 3,
        decimals: 2,
        isActive: true,
    },
    MXN: {
        key: 'mx',
        value: 'MXN',
        flag: 'mx',
        text: 'Peso Mexicano',
        img: 'mexico',
        alias: 'MXN',
        isCrypto: false,
        symbol: 'MXN$',
        priority: 4,
        decimals: 2,
        isActive: true,
    },
    ETH: {
        key: 'eth',
        value: 'ETH',
        icon: 'ethereum',
        text: 'Ether',
        img: 'eth',
        alias: 'ETH',
        isCrypto: true,
        symbol: 'Eth',
        priority: 14,
        decimals: 8,
        isActive: true,
    },
    BTC: {
        key: 'btc',
        value: 'BTC',
        icon: 'bitcoin',
        text: 'Bitcoin',
        img: 'btc',
        alias: 'BTC',
        isCrypto: true,
        symbol: 'Ƀ',
        priority: 15,
        decimals: 8,
        isActive: true,
    },
    USDT: {
        key: 'usdt',
        value: 'USDT',
        icon: 'usdt',
        text: 'USD Tether',
        img: 'tether',
        alias: 'USDT',
        isCrypto: true,
        symbol: '₮',
        priority: 20,
        decimals: 2,
        isActive: true,
        protocols: ['ERC20', 'TRC20']
    },
    CRC: {
        key: 'crc',
        value: 'CRC',
        flag: 'cr',
        text: 'Colón costarricense',
        img: 'costa_rica',
        alias: 'CRC',
        isCrypto: false,
        symbol: '₡',
        priority: 11,
        decimals: 2,
        isActive: false,
    },
    PAB: {
        key: 'pab',
        value: 'PAB',
        flag: 'pa',
        text: 'Balboa',
        img: 'panama',
        alias: 'PAB',
        isCrypto: false,
        symbol: 'B/.',
        priority: 12,
        decimals: 2,
        isActive: false,
    },
    PA_USD: {
        key: 'pa_usd',
        value: 'PA_USD',
        flag: 'pa',
        text: 'Dolár (Pánama)',
        img: 'panama',
        alias: 'PA_USD',
        isCrypto: false,
        symbol: '$',
        priority: 13,
        decimals: 2,
        isActive: true,
    },
    INR: {
        key: 'inr',
        value: 'INR',
        text: 'Rupia',
        img: 'rupia',
        alias: 'INR',
        priority: 14,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: false,
    },
    CAD: {
        key: 'ca',
        value: 'CAD',
        text: 'Dolar Canadiense',
        img: 'canada',
        alias: 'CAD',
        priority: 15,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: false,
    },
    CNY: {
        key: 'cny',
        value: 'CNY',
        text: 'Yuanes',
        img: 'china',
        alias: 'CNY',
        priority: 16,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: false,
    },
    RUB: {
        key: 'rub',
        value: 'RUB',
        text: 'Rublo ruso',
        img: 'rusia',
        alias: 'RUB',
        priority: 17,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: false,
    },
    JPY: {
        key: 'jpy',
        value: 'JPY',
        text: 'Yen japonés',
        img: 'japon',
        alias: 'JPY',
        priority: 18,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: false,
    },
    CHF: {
        key: 'chk',
        value: 'CHF',
        text: 'Franco suizo',
        img: 'switzerland',
        alias: 'CHF',
        priority: 19,
        isCrypto: false,
        symbol: '$',
        decimals: 2,
        isActive: true,
    },
    BCH: {
        key: 'bch',
        value: 'BCH',
        icon: 'bitcoin_cash',
        text: 'Bitcoin Cash',
        img: 'btc_cash',
        alias: 'BTC CASH',
        isCrypto: true,
        symbol: 'Ƀ',
        priority: 21,
        decimals: 8,
        isActive: true,
    },
    DOGE: {
        key: 'doge',
        value: 'DOGE',
        icon: 'doge',
        text: 'Dogecoin',
        img: 'doge',
        alias: 'DOGE',
        isCrypto: true,
        symbol: 'Ð',
        priority: 22,
        decimals: 8,
        isActive: true,
    },
    LTC: {
        key: 'ltc',
        value: 'LTC',
        icon: 'ltc',
        text: 'Litecoin',
        img: 'ltc',
        alias: 'LTC',
        isCrypto: true,
        symbol: 'Ł',
        priority: 23,
        decimals: 8,
        isActive: true,
    },
    DASH: {
        key: 'dash',
        value: 'DASH',
        icon: 'dash',
        text: 'Dash',
        img: 'dash',
        alias: 'DASH',
        isCrypto: true,
        symbol: 'dash',
        priority: 24,
        decimals: 8,
        isActive: true,
    },
    XRP: {
        key: 'xrp',
        value: 'XRP',
        icon: 'xrp',
        text: 'Ripple',
        img: 'xrp',
        alias: 'XRP',
        isCrypto: true,
        symbol: 'xrp',
        priority: 25,
        decimals: 8,
        isActive: true,
    },
    KKT: {
        key: 'kkt',
        value: 'KKT',
        icon: 'kkt',
        text: 'Kai Kai Token',
        img: 'kkt',
        alias: 'KKT',
        isCrypto: true,
        symbol: 'kkt',
        priority: 137,
        decimals: 8,
        isActive: true,
    },
}
